<?php

namespace SalimHosen\Core\Seeders;

use SalimHosen\Core\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [
                'name' => 'Afghanistan',
                'arabic_name' => '',
                'iso_code_2' => 'af',
                'iso_code_3' => '',
                'flag' => 'af.png',
                'country_code' => '',
                'slug' => 'afghanistan',
                'is_active' => false,
            ],
            [
                'name' => 'Åland Islands',
                'arabic_name' => '',
                'iso_code_2' => 'ax',
                'iso_code_3' => '',
                'flag' => 'ax.png',
                'country_code' => '',
                'slug' => 'aland-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Albania',
                'arabic_name' => '',
                'iso_code_2' => 'al',
                'iso_code_3' => '',
                'flag' => 'al.png',
                'country_code' => '',
                'slug' => 'albania',
                'is_active' => false,
            ],
            [
                'name' => 'Algeria',
                'arabic_name' => '',
                'iso_code_2' => 'dz',
                'iso_code_3' => '',
                'flag' => 'dz.png',
                'country_code' => '',
                'slug' => 'algeria',
                'is_active' => false,
            ],
            [
                'name' => 'American Samoa',
                'arabic_name' => '',
                'iso_code_2' => 'as',
                'iso_code_3' => '',
                'flag' => 'as.png',
                'country_code' => '',
                'slug' => 'american-samoa',
                'is_active' => false,
            ],
            [
                'name' => 'Andorra',
                'arabic_name' => '',
                'iso_code_2' => 'ad',
                'iso_code_3' => '',
                'flag' => 'ad.png',
                'country_code' => '',
                'slug' => 'andorra',
                'is_active' => false,
            ],
            [
                'name' => 'Angola',
                'arabic_name' => '',
                'iso_code_2' => 'ao',
                'iso_code_3' => '',
                'flag' => 'ao.png',
                'country_code' => '',
                'slug' => 'angola',
                'is_active' => false,
            ],
            [
                'name' => 'Anguilla',
                'arabic_name' => '',
                'iso_code_2' => 'ai',
                'iso_code_3' => '',
                'flag' => 'ai.png',
                'country_code' => '',
                'slug' => 'anguilla',
                'is_active' => false,
            ],
            [
                'name' => 'Antarctica',
                'arabic_name' => '',
                'iso_code_2' => 'aq',
                'iso_code_3' => '',
                'flag' => 'aq.png',
                'country_code' => '',
                'slug' => 'antarctica',
                'is_active' => false,
            ],
            [
                'name' => 'Antigua and Barbuda',
                'arabic_name' => '',
                'iso_code_2' => 'ag',
                'iso_code_3' => '',
                'flag' => 'ag.png',
                'country_code' => '',
                'slug' => 'antigua-and-barbuda',
                'is_active' => false,
            ],
            [
                'name' => 'Argentina',
                'arabic_name' => '',
                'iso_code_2' => 'ar',
                'iso_code_3' => '',
                'flag' => 'ar.png',
                'country_code' => '',
                'slug' => 'argentina',
                'is_active' => false,
            ],
            [
                'name' => 'Armenia',
                'arabic_name' => '',
                'iso_code_2' => 'am',
                'iso_code_3' => '',
                'flag' => 'am.png',
                'country_code' => '',
                'slug' => 'armenia',
                'is_active' => false,
            ],
            [
                'name' => 'Aruba',
                'arabic_name' => '',
                'iso_code_2' => 'aw',
                'iso_code_3' => '',
                'flag' => 'aw.png',
                'country_code' => '',
                'slug' => 'aruba',
                'is_active' => false,
            ],
            [
                'name' => 'Australia',
                'arabic_name' => '',
                'iso_code_2' => 'au',
                'iso_code_3' => '',
                'flag' => 'au.png',
                'country_code' => '',
                'slug' => 'australia',
                'is_active' => false,
            ],
            [
                'name' => 'Austria',
                'arabic_name' => '',
                'iso_code_2' => 'at',
                'iso_code_3' => '',
                'flag' => 'at.png',
                'country_code' => '',
                'slug' => 'austria',
                'is_active' => false,
            ],
            [
                'name' => 'Azerbaijan',
                'arabic_name' => '',
                'iso_code_2' => 'az',
                'iso_code_3' => '',
                'flag' => 'az.png',
                'country_code' => '',
                'slug' => 'azerbaijan',
                'is_active' => false,
            ],
            [
                'name' => 'Bahamas',
                'arabic_name' => '',
                'iso_code_2' => 'bs',
                'iso_code_3' => '',
                'flag' => 'bs.png',
                'country_code' => '',
                'slug' => 'bahamas',
                'is_active' => false,
            ],
            [
                'name' => 'Bahrain',
                'arabic_name' => '',
                'iso_code_2' => 'bh',
                'iso_code_3' => '',
                'flag' => 'bh.png',
                'country_code' => '',
                'slug' => 'bahrain',
                'is_active' => false,
            ],
            [
                'name' => 'Bangladesh',
                'arabic_name' => 'بنغلاديش',
                'iso_code_2' => 'bd',
                'iso_code_3' => 'ban',
                'flag' => 'bd.png',
                'country_code' => '+880',
                'slug' => 'bangladesh',
                'is_active' => true,
            ],
            [
                'name' => 'Barbados',
                'arabic_name' => '',
                'iso_code_2' => 'bb',
                'iso_code_3' => '',
                'flag' => 'bb.png',
                'country_code' => '',
                'slug' => 'barbados',
                'is_active' => false,
            ],
            [
                'name' => 'Belarus',
                'arabic_name' => '',
                'iso_code_2' => 'by',
                'iso_code_3' => '',
                'flag' => 'by.png',
                'country_code' => '',
                'slug' => 'belarus',
                'is_active' => false,
            ],
            [
                'name' => 'Belgium',
                'arabic_name' => '',
                'iso_code_2' => 'be',
                'iso_code_3' => '',
                'flag' => 'be.png',
                'country_code' => '',
                'slug' => 'belgium',
                'is_active' => false,
            ],
            [
                'name' => 'Belize',
                'arabic_name' => '',
                'iso_code_2' => 'bz',
                'iso_code_3' => '',
                'flag' => 'bz.png',
                'country_code' => '',
                'slug' => 'belize',
                'is_active' => false,
            ],
            [
                'name' => 'Benin',
                'arabic_name' => '',
                'iso_code_2' => 'bj',
                'iso_code_3' => '',
                'flag' => 'bj.png',
                'country_code' => '',
                'slug' => 'benin',
                'is_active' => false,
            ],
            [
                'name' => 'Bermuda',
                'arabic_name' => '',
                'iso_code_2' => 'bm',
                'iso_code_3' => '',
                'flag' => 'bm.png',
                'country_code' => '',
                'slug' => 'bermuda',
                'is_active' => false,
            ],
            [
                'name' => 'Bhutan',
                'arabic_name' => '',
                'iso_code_2' => 'bt',
                'iso_code_3' => '',
                'flag' => 'bt.png',
                'country_code' => '',
                'slug' => 'bhutan',
                'is_active' => false,
            ],
            [
                'name' => 'Bolivia',
                'arabic_name' => '',
                'iso_code_2' => 'bo',
                'iso_code_3' => '',
                'flag' => 'bo.png',
                'country_code' => '',
                'slug' => 'bolivia',
                'is_active' => false,
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'arabic_name' => '',
                'iso_code_2' => 'ba',
                'iso_code_3' => '',
                'flag' => 'ba.png',
                'country_code' => '',
                'slug' => 'bosnia-and-herzegovina',
                'is_active' => false,
            ],
            [
                'name' => 'Botswana',
                'arabic_name' => '',
                'iso_code_2' => 'bw',
                'iso_code_3' => '',
                'flag' => 'bw.png',
                'country_code' => '',
                'slug' => 'botswana',
                'is_active' => false,
            ],
            [
                'name' => 'Bouvet Island',
                'arabic_name' => '',
                'iso_code_2' => 'bv',
                'iso_code_3' => '',
                'flag' => 'bv.png',
                'country_code' => '',
                'slug' => 'bouvet-island',
                'is_active' => false,
            ],
            [
                'name' => 'Brazil',
                'arabic_name' => '',
                'iso_code_2' => 'br',
                'iso_code_3' => '',
                'flag' => 'br.png',
                'country_code' => '',
                'slug' => 'brazil',
                'is_active' => false,
            ],
            [
                'name' => 'British Indian Ocean Territory',
                'arabic_name' => '',
                'iso_code_2' => 'io',
                'iso_code_3' => '',
                'flag' => 'io.png',
                'country_code' => '',
                'slug' => 'british-indian-ocean-territory',
                'is_active' => false,
            ],
            [
                'name' => 'British Virgin Islands',
                'arabic_name' => '',
                'iso_code_2' => 'vg',
                'iso_code_3' => '',
                'flag' => 'vg.png',
                'country_code' => '',
                'slug' => 'british-virgin-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Brunei',
                'arabic_name' => '',
                'iso_code_2' => 'bn',
                'iso_code_3' => '',
                'flag' => 'bn.png',
                'country_code' => '',
                'slug' => 'brunei',
                'is_active' => false,
            ],
            [
                'name' => 'Bulgaria',
                'arabic_name' => '',
                'iso_code_2' => 'bg',
                'iso_code_3' => '',
                'flag' => 'bg.png',
                'country_code' => '',
                'slug' => 'bulgaria',
                'is_active' => false,
            ],
            [
                'name' => 'Burkina Faso',
                'arabic_name' => '',
                'iso_code_2' => 'bf',
                'iso_code_3' => '',
                'flag' => 'bf.png',
                'country_code' => '',
                'slug' => 'burkina-faso',
                'is_active' => false,
            ],
            [
                'name' => 'Burundi',
                'arabic_name' => '',
                'iso_code_2' => 'bi',
                'iso_code_3' => '',
                'flag' => 'bi.png',
                'country_code' => '',
                'slug' => 'burundi',
                'is_active' => false,
            ],
            [
                'name' => 'Cambodia',
                'arabic_name' => '',
                'iso_code_2' => 'kh',
                'iso_code_3' => '',
                'flag' => 'kh.png',
                'country_code' => '',
                'slug' => 'cambodia',
                'is_active' => false,
            ],
            [
                'name' => 'Cameroon',
                'arabic_name' => '',
                'iso_code_2' => 'cm',
                'iso_code_3' => '',
                'flag' => 'cm.png',
                'country_code' => '',
                'slug' => 'cameroon',
                'is_active' => false,
            ],
            [
                'name' => 'Canada',
                'arabic_name' => '',
                'iso_code_2' => 'ca',
                'iso_code_3' => '',
                'flag' => 'ca.png',
                'country_code' => '',
                'slug' => 'canada',
                'is_active' => false,
            ],
            [
                'name' => 'Cape Verde',
                'arabic_name' => '',
                'iso_code_2' => 'cv',
                'iso_code_3' => '',
                'flag' => 'cv.png',
                'country_code' => '',
                'slug' => 'cape-verde',
                'is_active' => false,
            ],
            [
                'name' => 'Caribbean Netherlands',
                'arabic_name' => '',
                'iso_code_2' => 'bq',
                'iso_code_3' => '',
                'flag' => 'bq.png',
                'country_code' => '',
                'slug' => 'caribbean-netherlands',
                'is_active' => false,
            ],
            [
                'name' => 'Cayman Islands',
                'arabic_name' => '',
                'iso_code_2' => 'ky',
                'iso_code_3' => '',
                'flag' => 'ky.png',
                'country_code' => '',
                'slug' => 'cayman-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Central African Republic',
                'arabic_name' => '',
                'iso_code_2' => 'cf',
                'iso_code_3' => '',
                'flag' => 'cf.png',
                'country_code' => '',
                'slug' => 'central-african-republic',
                'is_active' => false,
            ],
            [
                'name' => 'Chad',
                'arabic_name' => '',
                'iso_code_2' => 'td',
                'iso_code_3' => '',
                'flag' => 'td.png',
                'country_code' => '',
                'slug' => 'chad',
                'is_active' => false,
            ],
            [
                'name' => 'Chile',
                'arabic_name' => '',
                'iso_code_2' => 'cl',
                'iso_code_3' => '',
                'flag' => 'cl.png',
                'country_code' => '',
                'slug' => 'chile',
                'is_active' => false,
            ],
            [
                'name' => 'China',
                'arabic_name' => '',
                'iso_code_2' => 'cn',
                'iso_code_3' => '',
                'flag' => 'cn.png',
                'country_code' => '',
                'slug' => 'china',
                'is_active' => false,
            ],
            [
                'name' => 'Christmas Island',
                'arabic_name' => '',
                'iso_code_2' => 'cx',
                'iso_code_3' => '',
                'flag' => 'cx.png',
                'country_code' => '',
                'slug' => 'christmas-island',
                'is_active' => false,
            ],
            [
                'name' => 'Cocos Islands',
                'arabic_name' => '',
                'iso_code_2' => 'cc',
                'iso_code_3' => '',
                'flag' => 'cc.png',
                'country_code' => '',
                'slug' => 'cocos-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Colombia',
                'arabic_name' => '',
                'iso_code_2' => 'co',
                'iso_code_3' => '',
                'flag' => 'co.png',
                'country_code' => '',
                'slug' => 'colombia',
                'is_active' => false,
            ],
            [
                'name' => 'Comoros',
                'arabic_name' => '',
                'iso_code_2' => 'km',
                'iso_code_3' => '',
                'flag' => 'km.png',
                'country_code' => '',
                'slug' => 'comoros',
                'is_active' => false,
            ],
            [
                'name' => 'Cook Islands',
                'arabic_name' => '',
                'iso_code_2' => 'ck',
                'iso_code_3' => '',
                'flag' => 'ck.png',
                'country_code' => '',
                'slug' => 'cook-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Costa Rica',
                'arabic_name' => '',
                'iso_code_2' => 'cr',
                'iso_code_3' => '',
                'flag' => 'cr.png',
                'country_code' => '',
                'slug' => 'costa-rica',
                'is_active' => false,
            ],
            [
                'name' => "Côte d'Ivoire",
                'arabic_name' => '',
                'iso_code_2' => 'ci',
                'iso_code_3' => '',
                'flag' => 'ci.png',
                'country_code' => '',
                'slug' => 'cote-divoire',
                'is_active' => false,
            ],
            [
                'name' => 'Croatia',
                'arabic_name' => '',
                'iso_code_2' => 'hr',
                'iso_code_3' => '',
                'flag' => 'hr.png',
                'country_code' => '',
                'slug' => 'croatia',
                'is_active' => false,
            ],
            [
                'name' => 'Cuba',
                'arabic_name' => '',
                'iso_code_2' => 'cu',
                'iso_code_3' => '',
                'flag' => 'cu.png',
                'country_code' => '',
                'slug' => 'cuba',
                'is_active' => false,
            ],
            [
                'name' => 'Curaçao',
                'arabic_name' => '',
                'iso_code_2' => 'cw',
                'iso_code_3' => '',
                'flag' => 'cw.png',
                'country_code' => '',
                'slug' => 'curacao',
                'is_active' => false,
            ],
            [
                'name' => 'Cyprus',
                'arabic_name' => '',
                'iso_code_2' => 'cy',
                'iso_code_3' => '',
                'flag' => 'cy.png',
                'country_code' => '',
                'slug' => 'cyprus',
                'is_active' => false,
            ],
            [
                'name' => 'Czechia',
                'arabic_name' => '',
                'iso_code_2' => 'cz',
                'iso_code_3' => '',
                'flag' => 'cz.png',
                'country_code' => '',
                'slug' => 'czechia',
                'is_active' => false,
            ],
            [
                'name' => 'Denmark',
                'arabic_name' => '',
                'iso_code_2' => 'dk',
                'iso_code_3' => '',
                'flag' => 'dk.png',
                'country_code' => '',
                'slug' => 'denmark',
                'is_active' => false,
            ],
            [
                'name' => 'Djibouti',
                'arabic_name' => '',
                'iso_code_2' => 'dj',
                'iso_code_3' => '',
                'flag' => 'dj.png',
                'country_code' => '',
                'slug' => 'djibouti',
                'is_active' => false,
            ],
            [
                'name' => 'Dominica',
                'arabic_name' => '',
                'iso_code_2' => 'dm',
                'iso_code_3' => '',
                'flag' => 'dm.png',
                'country_code' => '',
                'slug' => 'dominica',
                'is_active' => false,
            ],
            [
                'name' => 'Dominican Republic',
                'arabic_name' => '',
                'iso_code_2' => 'do',
                'iso_code_3' => '',
                'flag' => 'do.png',
                'country_code' => '',
                'slug' => 'dominican-republic',
                'is_active' => false,
            ],
            [
                'name' => 'DR Congo',
                'arabic_name' => '',
                'iso_code_2' => 'cd',
                'iso_code_3' => '',
                'flag' => 'cd.png',
                'country_code' => '',
                'slug' => 'dr-congo',
                'is_active' => false,
            ],
            [
                'name' => 'Ecuador',
                'arabic_name' => '',
                'iso_code_2' => 'ec',
                'iso_code_3' => '',
                'flag' => 'ec.png',
                'country_code' => '',
                'slug' => 'ecuador',
                'is_active' => false,
            ],
            [
                'name' => 'Egypt',
                'arabic_name' => '',
                'iso_code_2' => 'eg',
                'iso_code_3' => '',
                'flag' => 'eg.png',
                'country_code' => '',
                'slug' => 'egypt',
                'is_active' => false,
            ],
            [
                'name' => 'El Salvador',
                'arabic_name' => '',
                'iso_code_2' => 'sv',
                'iso_code_3' => '',
                'flag' => 'sv.png',
                'country_code' => '',
                'slug' => 'el-salvador',
                'is_active' => false,
            ],
            [
                'name' => 'England',
                'arabic_name' => '',
                'iso_code_2' => 'gb-eng',
                'iso_code_3' => '',
                'flag' => 'gb-eng.png',
                'country_code' => '',
                'slug' => 'england',
                'is_active' => false,
            ],
            [
                'name' => 'Equatorial Guinea',
                'arabic_name' => '',
                'iso_code_2' => 'gq',
                'iso_code_3' => '',
                'flag' => 'gq.png',
                'country_code' => '',
                'slug' => 'equatorial-guinea',
                'is_active' => false,
            ],
            [
                'name' => 'Eritrea',
                'arabic_name' => '',
                'iso_code_2' => 'er',
                'iso_code_3' => '',
                'flag' => 'er.png',
                'country_code' => '',
                'slug' => 'eritrea',
                'is_active' => false,
            ],
            [
                'name' => 'Estonia',
                'arabic_name' => '',
                'iso_code_2' => 'ee',
                'iso_code_3' => '',
                'flag' => 'ee.png',
                'country_code' => '',
                'slug' => 'estonia',
                'is_active' => false,
            ],
            [
                'name' => 'Eswatini',
                'arabic_name' => '',
                'iso_code_2' => 'sz',
                'iso_code_3' => '',
                'flag' => 'sz.png',
                'country_code' => '',
                'slug' => 'eswatini',
                'is_active' => false,
            ],
            [
                'name' => 'Ethiopia',
                'arabic_name' => '',
                'iso_code_2' => 'et',
                'iso_code_3' => '',
                'flag' => 'et.png',
                'country_code' => '',
                'slug' => 'ethiopia',
                'is_active' => false,
            ],
            [
                'name' => 'Falkland Islands',
                'arabic_name' => '',
                'iso_code_2' => 'fk',
                'iso_code_3' => '',
                'flag' => 'fk.png',
                'country_code' => '',
                'slug' => 'falkland-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Faroe Islands',
                'arabic_name' => '',
                'iso_code_2' => 'fo',
                'iso_code_3' => '',
                'flag' => 'fo.png',
                'country_code' => '',
                'slug' => 'faroe-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Fiji',
                'arabic_name' => '',
                'iso_code_2' => 'fj',
                'iso_code_3' => '',
                'flag' => 'fj.png',
                'country_code' => '',
                'slug' => 'fiji',
                'is_active' => false,
            ],
            [
                'name' => 'Finland',
                'arabic_name' => '',
                'iso_code_2' => 'fi',
                'iso_code_3' => '',
                'flag' => 'fi.png',
                'country_code' => '',
                'slug' => 'finland',
                'is_active' => false,
            ],
            [
                'name' => 'France',
                'arabic_name' => '',
                'iso_code_2' => 'fr',
                'iso_code_3' => '',
                'flag' => 'fr.png',
                'country_code' => '',
                'slug' => 'france',
                'is_active' => false,
            ],
            [
                'name' => 'French Guiana',
                'arabic_name' => '',
                'iso_code_2' => 'gf',
                'iso_code_3' => '',
                'flag' => 'gf.png',
                'country_code' => '',
                'slug' => 'french-guiana',
                'is_active' => false,
            ],
            [
                'name' => 'French Polynesia',
                'arabic_name' => '',
                'iso_code_2' => 'pf',
                'iso_code_3' => '',
                'flag' => 'pf.png',
                'country_code' => '',
                'slug' => 'french-polynesia',
                'is_active' => false,
            ],
            [
                'name' => 'French Southern and Antarctic Lands',
                'arabic_name' => '',
                'iso_code_2' => 'tf',
                'iso_code_3' => '',
                'flag' => 'tf.png',
                'country_code' => '',
                'slug' => 'french-southern-and-antarctic-lands',
                'is_active' => false,
            ],
            [
                'name' => 'Gabon',
                'arabic_name' => '',
                'iso_code_2' => 'ga',
                'iso_code_3' => '',
                'flag' => 'ga.png',
                'country_code' => '',
                'slug' => 'gabon',
                'is_active' => false,
            ],
            [
                'name' => 'Gambia',
                'arabic_name' => '',
                'iso_code_2' => 'gm',
                'iso_code_3' => '',
                'flag' => 'gm.png',
                'country_code' => '',
                'slug' => 'gambia',
                'is_active' => false,
            ],
            [
                'name' => 'Georgia',
                'arabic_name' => '',
                'iso_code_2' => 'ge',
                'iso_code_3' => '',
                'flag' => 'ge.png',
                'country_code' => '',
                'slug' => 'georgia',
                'is_active' => false,
            ],
            [
                'name' => 'Germany',
                'arabic_name' => '',
                'iso_code_2' => 'de',
                'iso_code_3' => '',
                'flag' => 'de.png',
                'country_code' => '',
                'slug' => 'germany',
                'is_active' => false,
            ],
            [
                'name' => 'Ghana',
                'arabic_name' => '',
                'iso_code_2' => 'gh',
                'iso_code_3' => '',
                'flag' => 'gh.png',
                'country_code' => '',
                'slug' => 'ghana',
                'is_active' => false,
            ],
            [
                'name' => 'Gibraltar',
                'arabic_name' => '',
                'iso_code_2' => 'gi',
                'iso_code_3' => '',
                'flag' => 'gi.png',
                'country_code' => '',
                'slug' => 'gibraltar',
                'is_active' => false,
            ],
            [
                'name' => 'Greece',
                'arabic_name' => '',
                'iso_code_2' => 'gr',
                'iso_code_3' => '',
                'flag' => 'gr.png',
                'country_code' => '',
                'slug' => 'greece',
                'is_active' => false,
            ],
            [
                'name' => 'Greenland',
                'arabic_name' => '',
                'iso_code_2' => 'gl',
                'iso_code_3' => '',
                'flag' => 'gl.png',
                'country_code' => '',
                'slug' => 'greenland',
                'is_active' => false,
            ],
            [
                'name' => 'Grenada',
                'arabic_name' => '',
                'iso_code_2' => 'gd',
                'iso_code_3' => '',
                'flag' => 'gd.png',
                'country_code' => '',
                'slug' => 'grenada',
                'is_active' => false,
            ],
            [
                'name' => 'Guadeloupe',
                'arabic_name' => '',
                'iso_code_2' => 'gp',
                'iso_code_3' => '',
                'flag' => 'gp.png',
                'country_code' => '',
                'slug' => 'guadeloupe',
                'is_active' => false,
            ],
            [
                'name' => 'Guam',
                'arabic_name' => '',
                'iso_code_2' => 'gu',
                'iso_code_3' => '',
                'flag' => 'gu.png',
                'country_code' => '',
                'slug' => 'guam',
                'is_active' => false,
            ],
            [
                'name' => 'Guatemala',
                'arabic_name' => '',
                'iso_code_2' => 'gt',
                'iso_code_3' => '',
                'flag' => 'gt.png',
                'country_code' => '',
                'slug' => 'guatemala',
                'is_active' => false,
            ],
            [
                'name' => 'Guernsey',
                'arabic_name' => '',
                'iso_code_2' => 'gg',
                'iso_code_3' => '',
                'flag' => 'gg.png',
                'country_code' => '',
                'slug' => 'guernsey',
                'is_active' => false,
            ],
            [
                'name' => 'Guinea',
                'arabic_name' => '',
                'iso_code_2' => 'gn',
                'iso_code_3' => '',
                'flag' => 'gn.png',
                'country_code' => '',
                'slug' => 'guinea',
                'is_active' => false,
            ],
            [
                'name' => 'Guinea-Bissau',
                'arabic_name' => '',
                'iso_code_2' => 'gw',
                'iso_code_3' => '',
                'flag' => 'gw.png',
                'country_code' => '',
                'slug' => 'guinea-bissau',
                'is_active' => false,
            ],
            [
                'name' => 'Guyana',
                'arabic_name' => '',
                'iso_code_2' => 'gy',
                'iso_code_3' => '',
                'flag' => 'gy.png',
                'country_code' => '',
                'slug' => 'guyana',
                'is_active' => false,
            ],
            [
                'name' => 'Haiti',
                'arabic_name' => '',
                'iso_code_2' => 'ht',
                'iso_code_3' => '',
                'flag' => 'ht.png',
                'country_code' => '',
                'slug' => 'haiti',
                'is_active' => false,
            ],
            [
                'name' => 'Heard Island and McDonald Islands',
                'arabic_name' => '',
                'iso_code_2' => 'hm',
                'iso_code_3' => '',
                'flag' => 'hm.png',
                'country_code' => '',
                'slug' => 'heard-island-and-mcdonald-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Honduras',
                'arabic_name' => '',
                'iso_code_2' => 'hn',
                'iso_code_3' => '',
                'flag' => 'hn.png',
                'country_code' => '',
                'slug' => 'honduras',
                'is_active' => false,
            ],
            [
                'name' => 'Hong Kong',
                'arabic_name' => '',
                'iso_code_2' => 'hk',
                'iso_code_3' => '',
                'flag' => 'hk.png',
                'country_code' => '',
                'slug' => 'hong-kong',
                'is_active' => false,
            ],
            [
                'name' => 'Hungary',
                'arabic_name' => '',
                'iso_code_2' => 'hu',
                'iso_code_3' => '',
                'flag' => 'hu.png',
                'country_code' => '',
                'slug' => 'hungary',
                'is_active' => false,
            ],
            [
                'name' => 'Iceland',
                'arabic_name' => '',
                'iso_code_2' => 'is',
                'iso_code_3' => '',
                'flag' => 'is.png',
                'country_code' => '',
                'slug' => 'iceland',
                'is_active' => false,
            ],
            [
                'name' => 'India',
                'arabic_name' => '',
                'iso_code_2' => 'in',
                'iso_code_3' => '',
                'flag' => 'in.png',
                'country_code' => '',
                'slug' => 'india',
                'is_active' => false,
            ],
            [
                'name' => 'Indonesia',
                'arabic_name' => '',
                'iso_code_2' => 'id',
                'iso_code_3' => '',
                'flag' => 'id.png',
                'country_code' => '',
                'slug' => 'indonesia',
                'is_active' => false,
            ],
            [
                'name' => 'Iran',
                'arabic_name' => '',
                'iso_code_2' => 'ir',
                'iso_code_3' => '',
                'flag' => 'ir.png',
                'country_code' => '',
                'slug' => 'iran',
                'is_active' => false,
            ],
            [
                'name' => 'Iraq',
                'arabic_name' => '',
                'iso_code_2' => 'iq',
                'iso_code_3' => '',
                'flag' => 'iq.png',
                'country_code' => '',
                'slug' => 'iraq',
                'is_active' => false,
            ],
            [
                'name' => 'Ireland',
                'arabic_name' => '',
                'iso_code_2' => 'ie',
                'iso_code_3' => '',
                'flag' => 'ie.png',
                'country_code' => '',
                'slug' => 'ireland',
                'is_active' => false,
            ],
            [
                'name' => 'Isle of Man',
                'arabic_name' => '',
                'iso_code_2' => 'im',
                'iso_code_3' => '',
                'flag' => 'im.png',
                'country_code' => '',
                'slug' => 'isle-of-man',
                'is_active' => false,
            ],
            [
                'name' => 'Israel',
                'arabic_name' => '',
                'iso_code_2' => 'il',
                'iso_code_3' => '',
                'flag' => 'il.png',
                'country_code' => '',
                'slug' => 'israel',
                'is_active' => false,
            ],
            [
                'name' => 'Italy',
                'arabic_name' => '',
                'iso_code_2' => 'it',
                'iso_code_3' => '',
                'flag' => 'it.png',
                'country_code' => '',
                'slug' => 'italy',
                'is_active' => false,
            ],
            [
                'name' => 'Jamaica',
                'arabic_name' => '',
                'iso_code_2' => 'jm',
                'iso_code_3' => '',
                'flag' => 'jm.png',
                'country_code' => '',
                'slug' => 'jamaica',
                'is_active' => false,
            ],
            [
                'name' => 'Japan',
                'arabic_name' => '',
                'iso_code_2' => 'jp',
                'iso_code_3' => '',
                'flag' => 'jp.png',
                'country_code' => '',
                'slug' => 'japan',
                'is_active' => false,
            ],
            [
                'name' => 'Jersey',
                'arabic_name' => '',
                'iso_code_2' => 'je',
                'iso_code_3' => '',
                'flag' => 'je.png',
                'country_code' => '',
                'slug' => 'jersey',
                'is_active' => false,
            ],
            [
                'name' => 'Jordan',
                'arabic_name' => '',
                'iso_code_2' => 'jo',
                'iso_code_3' => '',
                'flag' => 'jo.png',
                'country_code' => '',
                'slug' => 'jordan',
                'is_active' => false,
            ],
            [
                'name' => 'Kazakhstan',
                'arabic_name' => '',
                'iso_code_2' => 'kz',
                'iso_code_3' => '',
                'flag' => 'kz.png',
                'country_code' => '',
                'slug' => 'kazakhstan',
                'is_active' => false,
            ],
            [
                'name' => 'Kenya',
                'arabic_name' => '',
                'iso_code_2' => 'ke',
                'iso_code_3' => '',
                'flag' => 'ke.png',
                'country_code' => '',
                'slug' => 'kenya',
                'is_active' => false,
            ],
            [
                'name' => 'Kiribati',
                'arabic_name' => '',
                'iso_code_2' => 'ki',
                'iso_code_3' => '',
                'flag' => 'ki.png',
                'country_code' => '',
                'slug' => 'kiribati',
                'is_active' => false,
            ],
            [
                'name' => 'Kosovo',
                'arabic_name' => '',
                'iso_code_2' => 'xk',
                'iso_code_3' => '',
                'flag' => 'xk.png',
                'country_code' => '',
                'slug' => 'kosovo',
                'is_active' => false,
            ],
            [
                'name' => 'Kuwait',
                'arabic_name' => '',
                'iso_code_2' => 'kw',
                'iso_code_3' => '',
                'flag' => 'kw.png',
                'country_code' => '',
                'slug' => 'kuwait',
                'is_active' => false,
            ],
            [
                'name' => 'Kyrgyzstan',
                'arabic_name' => '',
                'iso_code_2' => 'kg',
                'iso_code_3' => '',
                'flag' => 'kg.png',
                'country_code' => '',
                'slug' => 'kyrgyzstan',
                'is_active' => false,
            ],
            [
                'name' => 'Laos',
                'arabic_name' => '',
                'iso_code_2' => 'la',
                'iso_code_3' => '',
                'flag' => 'la.png',
                'country_code' => '',
                'slug' => 'laos',
                'is_active' => false,
            ],
            [
                'name' => 'Latvia',
                'arabic_name' => '',
                'iso_code_2' => 'lv',
                'iso_code_3' => '',
                'flag' => 'lv.png',
                'country_code' => '',
                'slug' => 'latvia',
                'is_active' => false,
            ],
            [
                'name' => 'Lebanon',
                'arabic_name' => '',
                'iso_code_2' => 'lb',
                'iso_code_3' => '',
                'flag' => 'lb.png',
                'country_code' => '',
                'slug' => 'lebanon',
                'is_active' => false,
            ],
            [
                'name' => 'Lesotho',
                'arabic_name' => '',
                'iso_code_2' => 'ls',
                'iso_code_3' => '',
                'flag' => 'ls.png',
                'country_code' => '',
                'slug' => 'lesotho',
                'is_active' => false,
            ],
            [
                'name' => 'Liberia',
                'arabic_name' => '',
                'iso_code_2' => 'lr',
                'iso_code_3' => '',
                'flag' => 'lr.png',
                'country_code' => '',
                'slug' => 'liberia',
                'is_active' => false,
            ],
            [
                'name' => 'Libya',
                'arabic_name' => '',
                'iso_code_2' => 'ly',
                'iso_code_3' => '',
                'flag' => 'ly.png',
                'country_code' => '',
                'slug' => 'libya',
                'is_active' => false,
            ],
            [
                'name' => 'Liechtenstein',
                'arabic_name' => '',
                'iso_code_2' => 'li',
                'iso_code_3' => '',
                'flag' => 'li.png',
                'country_code' => '',
                'slug' => 'liechtenstein',
                'is_active' => false,
            ],
            [
                'name' => 'Lithuania',
                'arabic_name' => '',
                'iso_code_2' => 'lt',
                'iso_code_3' => '',
                'flag' => 'lt.png',
                'country_code' => '',
                'slug' => 'lithuania',
                'is_active' => false,
            ],
            [
                'name' => 'Luxembourg',
                'arabic_name' => '',
                'iso_code_2' => 'lu',
                'iso_code_3' => '',
                'flag' => 'lu.png',
                'country_code' => '',
                'slug' => 'luxembourg',
                'is_active' => false,
            ],
            [
                'name' => 'Macau',
                'arabic_name' => '',
                'iso_code_2' => 'mo',
                'iso_code_3' => '',
                'flag' => 'mo.png',
                'country_code' => '',
                'slug' => 'macau',
                'is_active' => false,
            ],
            [
                'name' => 'Madagascar',
                'arabic_name' => '',
                'iso_code_2' => 'mg',
                'iso_code_3' => '',
                'flag' => 'mg.png',
                'country_code' => '',
                'slug' => 'madagascar',
                'is_active' => false,
            ],
            [
                'name' => 'Malawi',
                'arabic_name' => '',
                'iso_code_2' => 'mw',
                'iso_code_3' => '',
                'flag' => 'mw.png',
                'country_code' => '',
                'slug' => 'malawi',
                'is_active' => false,
            ],
            [
                'name' => 'Malaysia',
                'arabic_name' => '',
                'iso_code_2' => 'my',
                'iso_code_3' => '',
                'flag' => 'my.png',
                'country_code' => '',
                'slug' => 'malaysia',
                'is_active' => false,
            ],
            [
                'name' => 'Maldives',
                'arabic_name' => '',
                'iso_code_2' => 'mv',
                'iso_code_3' => '',
                'flag' => 'mv.png',
                'country_code' => '',
                'slug' => 'maldives',
                'is_active' => false,
            ],
            [
                'name' => 'Mali',
                'arabic_name' => '',
                'iso_code_2' => 'ml',
                'iso_code_3' => '',
                'flag' => 'ml.png',
                'country_code' => '',
                'slug' => 'mali',
                'is_active' => false,
            ],
            [
                'name' => 'Malta',
                'arabic_name' => '',
                'iso_code_2' => 'mt',
                'iso_code_3' => '',
                'flag' => 'mt.png',
                'country_code' => '',
                'slug' => 'malta',
                'is_active' => false,
            ],
            [
                'name' => 'Marshall Islands',
                'arabic_name' => '',
                'iso_code_2' => 'mh',
                'iso_code_3' => '',
                'flag' => 'mh.png',
                'country_code' => '',
                'slug' => 'marshall-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Martinique',
                'arabic_name' => '',
                'iso_code_2' => 'mq',
                'iso_code_3' => '',
                'flag' => 'mq.png',
                'country_code' => '',
                'slug' => 'martinique',
                'is_active' => false,
            ],
            [
                'name' => 'Mauritania',
                'arabic_name' => '',
                'iso_code_2' => 'mr',
                'iso_code_3' => '',
                'flag' => 'mr.png',
                'country_code' => '',
                'slug' => 'mauritania',
                'is_active' => false,
            ],
            [
                'name' => 'Mauritius',
                'arabic_name' => '',
                'iso_code_2' => 'mu',
                'iso_code_3' => '',
                'flag' => 'mu.png',
                'country_code' => '',
                'slug' => 'mauritius',
                'is_active' => false,
            ],
            [
                'name' => 'Mayotte',
                'arabic_name' => '',
                'iso_code_2' => 'yt',
                'iso_code_3' => '',
                'flag' => 'yt.png',
                'country_code' => '',
                'slug' => 'mayotte',
                'is_active' => false,
            ],
            [
                'name' => 'Mexico',
                'arabic_name' => '',
                'iso_code_2' => 'mx',
                'iso_code_3' => '',
                'flag' => 'mx.png',
                'country_code' => '',
                'slug' => 'mexico',
                'is_active' => false,
            ],
            [
                'name' => 'Micronesia',
                'arabic_name' => '',
                'iso_code_2' => 'fm',
                'iso_code_3' => '',
                'flag' => 'fm.png',
                'country_code' => '',
                'slug' => 'micronesia',
                'is_active' => false,
            ],
            [
                'name' => 'Moldova',
                'arabic_name' => '',
                'iso_code_2' => 'md',
                'iso_code_3' => '',
                'flag' => 'md.png',
                'country_code' => '',
                'slug' => 'moldova',
                'is_active' => false,
            ],
            [
                'name' => 'Monaco',
                'arabic_name' => '',
                'iso_code_2' => 'mc',
                'iso_code_3' => '',
                'flag' => 'mc.png',
                'country_code' => '',
                'slug' => 'monaco',
                'is_active' => false,
            ],
            [
                'name' => 'Mongolia',
                'arabic_name' => '',
                'iso_code_2' => 'mn',
                'iso_code_3' => '',
                'flag' => 'mn.png',
                'country_code' => '',
                'slug' => 'mongolia',
                'is_active' => false,
            ],
            [
                'name' => 'Montenegro',
                'arabic_name' => '',
                'iso_code_2' => 'me',
                'iso_code_3' => '',
                'flag' => 'me.png',
                'country_code' => '',
                'slug' => 'montenegro',
                'is_active' => false,
            ],
            [
                'name' => 'Montserrat',
                'arabic_name' => '',
                'iso_code_2' => 'ms',
                'iso_code_3' => '',
                'flag' => 'ms.png',
                'country_code' => '',
                'slug' => 'montserrat',
                'is_active' => false,
            ],
            [
                'name' => 'Morocco',
                'arabic_name' => '',
                'iso_code_2' => 'ma',
                'iso_code_3' => '',
                'flag' => 'ma.png',
                'country_code' => '',
                'slug' => 'morocco',
                'is_active' => false,
            ],
            [
                'name' => 'Mozambique',
                'arabic_name' => '',
                'iso_code_2' => 'mz',
                'iso_code_3' => '',
                'flag' => 'mz.png',
                'country_code' => '',
                'slug' => 'mozambique',
                'is_active' => false,
            ],
            [
                'name' => 'Myanmar',
                'arabic_name' => '',
                'iso_code_2' => 'mm',
                'iso_code_3' => '',
                'flag' => 'mm.png',
                'country_code' => '',
                'slug' => 'myanmar',
                'is_active' => false,
            ],
            [
                'name' => 'Namibia',
                'arabic_name' => '',
                'iso_code_2' => 'na',
                'iso_code_3' => '',
                'flag' => 'na.png',
                'country_code' => '',
                'slug' => 'namibia',
                'is_active' => false,
            ],
            [
                'name' => 'Nauru',
                'arabic_name' => '',
                'iso_code_2' => 'nr',
                'iso_code_3' => '',
                'flag' => 'nr.png',
                'country_code' => '',
                'slug' => 'nauru',
                'is_active' => false,
            ],
            [
                'name' => 'Nepal',
                'arabic_name' => '',
                'iso_code_2' => 'np',
                'iso_code_3' => '',
                'flag' => 'np.png',
                'country_code' => '',
                'slug' => 'nepal',
                'is_active' => false,
            ],
            [
                'name' => 'Netherlands',
                'arabic_name' => '',
                'iso_code_2' => 'nl',
                'iso_code_3' => '',
                'flag' => 'nl.png',
                'country_code' => '',
                'slug' => 'netherlands',
                'is_active' => false,
            ],
            [
                'name' => 'New Caledonia',
                'arabic_name' => '',
                'iso_code_2' => 'nc',
                'iso_code_3' => '',
                'flag' => 'nc.png',
                'country_code' => '',
                'slug' => 'new-caledonia',
                'is_active' => false,
            ],
            [
                'name' => 'New Zealand',
                'arabic_name' => '',
                'iso_code_2' => 'nz',
                'iso_code_3' => '',
                'flag' => 'nz.png',
                'country_code' => '',
                'slug' => 'new-zealand',
                'is_active' => false,
            ],
            [
                'name' => 'Nicaragua',
                'arabic_name' => '',
                'iso_code_2' => 'ni',
                'iso_code_3' => '',
                'flag' => 'ni.png',
                'country_code' => '',
                'slug' => 'nicaragua',
                'is_active' => false,
            ],
            [
                'name' => 'Niger',
                'arabic_name' => '',
                'iso_code_2' => 'ne',
                'iso_code_3' => '',
                'flag' => 'ne.png',
                'country_code' => '',
                'slug' => 'niger',
                'is_active' => false,
            ],
            [
                'name' => 'Nigeria',
                'arabic_name' => '',
                'iso_code_2' => 'ng',
                'iso_code_3' => '',
                'flag' => 'ng.png',
                'country_code' => '',
                'slug' => 'nigeria',
                'is_active' => false,
            ],
            [
                'name' => 'Niue',
                'arabic_name' => '',
                'iso_code_2' => 'nu',
                'iso_code_3' => '',
                'flag' => 'nu.png',
                'country_code' => '',
                'slug' => 'niue',
                'is_active' => false,
            ],
            [
                'name' => 'Norfolk Island',
                'arabic_name' => '',
                'iso_code_2' => 'nf',
                'iso_code_3' => '',
                'flag' => 'nf.png',
                'country_code' => '',
                'slug' => 'norfolk-island',
                'is_active' => false,
            ],
            [
                'name' => 'North Korea',
                'arabic_name' => '',
                'iso_code_2' => 'kp',
                'iso_code_3' => '',
                'flag' => 'kp.png',
                'country_code' => '',
                'slug' => 'north-korea',
                'is_active' => false,
            ],
            [
                'name' => 'North Macedonia',
                'arabic_name' => '',
                'iso_code_2' => 'mk',
                'iso_code_3' => '',
                'flag' => 'mk.png',
                'country_code' => '',
                'slug' => 'north-macedonia',
                'is_active' => false,
            ],
            [
                'name' => 'Northern Ireland',
                'arabic_name' => '',
                'iso_code_2' => 'gb-nir',
                'iso_code_3' => '',
                'flag' => 'gb-nir.png',
                'country_code' => '',
                'slug' => 'northern-ireland',
                'is_active' => false,
            ],
            [
                'name' => 'Northern Mariana Islands',
                'arabic_name' => '',
                'iso_code_2' => 'mp',
                'iso_code_3' => '',
                'flag' => 'mp.png',
                'country_code' => '',
                'slug' => 'northern-mariana-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Norway',
                'arabic_name' => '',
                'iso_code_2' => 'no',
                'iso_code_3' => '',
                'flag' => 'no.png',
                'country_code' => '',
                'slug' => 'norway',
                'is_active' => false,
            ],
            [
                'name' => 'Oman',
                'arabic_name' => '',
                'iso_code_2' => 'om',
                'iso_code_3' => '',
                'flag' => 'om.png',
                'country_code' => '',
                'slug' => 'oman',
                'is_active' => false,
            ],
            [
                'name' => 'Pakistan',
                'arabic_name' => '',
                'iso_code_2' => 'pk',
                'iso_code_3' => '',
                'flag' => 'pk.png',
                'country_code' => '',
                'slug' => 'pakistan',
                'is_active' => false,
            ],
            [
                'name' => 'Palau',
                'arabic_name' => '',
                'iso_code_2' => 'pw',
                'iso_code_3' => '',
                'flag' => 'pw.png',
                'country_code' => '',
                'slug' => 'palau',
                'is_active' => false,
            ],
            [
                'name' => 'Palestine',
                'arabic_name' => '',
                'iso_code_2' => 'ps',
                'iso_code_3' => '',
                'flag' => 'ps.png',
                'country_code' => '',
                'slug' => 'palestine',
                'is_active' => false,
            ],
            [
                'name' => 'Panama',
                'arabic_name' => '',
                'iso_code_2' => 'pa',
                'iso_code_3' => '',
                'flag' => 'pa.png',
                'country_code' => '',
                'slug' => 'panama',
                'is_active' => false,
            ],
            [
                'name' => 'Papua New Guinea',
                'arabic_name' => '',
                'iso_code_2' => 'pg',
                'iso_code_3' => '',
                'flag' => 'pg.png',
                'country_code' => '',
                'slug' => 'papua-new-guinea',
                'is_active' => false,
            ],
            [
                'name' => 'Paraguay',
                'arabic_name' => '',
                'iso_code_2' => 'py',
                'iso_code_3' => '',
                'flag' => 'py.png',
                'country_code' => '',
                'slug' => 'paraguay',
                'is_active' => false,
            ],
            [
                'name' => 'Peru',
                'arabic_name' => '',
                'iso_code_2' => 'pe',
                'iso_code_3' => '',
                'flag' => 'pe.png',
                'country_code' => '',
                'slug' => 'peru',
                'is_active' => false,
            ],
            [
                'name' => 'Philippines',
                'arabic_name' => '',
                'iso_code_2' => 'ph',
                'iso_code_3' => '',
                'flag' => 'ph.png',
                'country_code' => '',
                'slug' => 'philippines',
                'is_active' => false,
            ],
            [
                'name' => 'Pitcairn Islands',
                'arabic_name' => '',
                'iso_code_2' => 'pn',
                'iso_code_3' => '',
                'flag' => 'pn.png',
                'country_code' => '',
                'slug' => 'pitcairn-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Poland',
                'arabic_name' => '',
                'iso_code_2' => 'pl',
                'iso_code_3' => '',
                'flag' => 'pl.png',
                'country_code' => '',
                'slug' => 'poland',
                'is_active' => false,
            ],
            [
                'name' => 'Portugal',
                'arabic_name' => '',
                'iso_code_2' => 'pt',
                'iso_code_3' => '',
                'flag' => 'pt.png',
                'country_code' => '',
                'slug' => 'portugal',
                'is_active' => false,
            ],
            [
                'name' => 'Puerto Rico',
                'arabic_name' => '',
                'iso_code_2' => 'pr',
                'iso_code_3' => '',
                'flag' => 'pr.png',
                'country_code' => '',
                'slug' => 'puerto-rico',
                'is_active' => false,
            ],
            [
                'name' => 'Qatar',
                'arabic_name' => '',
                'iso_code_2' => 'qa',
                'iso_code_3' => '',
                'flag' => 'qa.png',
                'country_code' => '',
                'slug' => 'qatar',
                'is_active' => false,
            ],
            [
                'name' => 'Republic of the Congo',
                'arabic_name' => '',
                'iso_code_2' => 'cg',
                'iso_code_3' => '',
                'flag' => 'cg.png',
                'country_code' => '',
                'slug' => 'republic-of-the-congo',
                'is_active' => false,
            ],
            [
                'name' => 'Réunion',
                'arabic_name' => '',
                'iso_code_2' => 're',
                'iso_code_3' => '',
                'flag' => 're.png',
                'country_code' => '',
                'slug' => 'reunion',
                'is_active' => false,
            ],
            [
                'name' => 'Romania',
                'arabic_name' => '',
                'iso_code_2' => 'ro',
                'iso_code_3' => '',
                'flag' => 'ro.png',
                'country_code' => '',
                'slug' => 'romania',
                'is_active' => false,
            ],
            [
                'name' => 'Russia',
                'arabic_name' => '',
                'iso_code_2' => 'ru',
                'iso_code_3' => '',
                'flag' => 'ru.png',
                'country_code' => '',
                'slug' => 'russia',
                'is_active' => false,
            ],
            [
                'name' => 'Rwanda',
                'arabic_name' => '',
                'iso_code_2' => 'rw',
                'iso_code_3' => '',
                'flag' => 'rw.png',
                'country_code' => '',
                'slug' => 'rwanda',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Barthélemy',
                'arabic_name' => '',
                'iso_code_2' => 'bl',
                'iso_code_3' => '',
                'flag' => 'bl.png',
                'country_code' => '',
                'slug' => 'saint-barthelemy',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Helena, Ascension and Tristan da Cunha',
                'arabic_name' => '',
                'iso_code_2' => 'sh',
                'iso_code_3' => '',
                'flag' => 'sh.png',
                'country_code' => '',
                'slug' => 'saint-helena-ascension-and-tristan-da-cunha',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'arabic_name' => '',
                'iso_code_2' => 'kn',
                'iso_code_3' => '',
                'flag' => 'kn.png',
                'country_code' => '',
                'slug' => 'saint-kitts-and-nevis',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Lucia',
                'arabic_name' => '',
                'iso_code_2' => 'lc',
                'iso_code_3' => '',
                'flag' => 'lc.png',
                'country_code' => '',
                'slug' => 'saint-lucia',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Martin',
                'arabic_name' => '',
                'iso_code_2' => 'mf',
                'iso_code_3' => '',
                'flag' => 'mf.png',
                'country_code' => '',
                'slug' => 'saint-martin',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Pierre and Miquelon',
                'arabic_name' => '',
                'iso_code_2' => 'pm',
                'iso_code_3' => '',
                'flag' => 'pm.png',
                'country_code' => '',
                'slug' => 'saint-pierre-and-miquelon',
                'is_active' => false,
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'arabic_name' => '',
                'iso_code_2' => 'vc',
                'iso_code_3' => '',
                'flag' => 'vc.png',
                'country_code' => '',
                'slug' => 'saint-vincent-and-the-grenadines',
                'is_active' => false,
            ],
            [
                'name' => 'Samoa',
                'arabic_name' => '',
                'iso_code_2' => 'ws',
                'iso_code_3' => '',
                'flag' => 'ws.png',
                'country_code' => '',
                'slug' => 'samoa',
                'is_active' => false,
            ],
            [
                'name' => 'San Marino',
                'arabic_name' => '',
                'iso_code_2' => 'sm',
                'iso_code_3' => '',
                'flag' => 'sm.png',
                'country_code' => '',
                'slug' => 'san-marino',
                'is_active' => false,
            ],
            [
                'name' => 'São Tomé and Príncipe',
                'arabic_name' => '',
                'iso_code_2' => 'st',
                'iso_code_3' => '',
                'flag' => 'st.png',
                'country_code' => '',
                'slug' => 'sao-tome-and-principe',
                'is_active' => false,
            ],
            [
                'name' => 'Saudi Arabia',
                'arabic_name' => 'المملكة العربية السعودية',
                'iso_code_2' => 'sa',
                'iso_code_3' => 'sar',
                'flag' => 'sa.png',
                'country_code' => '+966',
                'slug' => 'saudi-arabia',
                'is_active' => true,
            ],
            [
                'name' => 'Scotland',
                'arabic_name' => '',
                'iso_code_2' => 'gb-sct',
                'iso_code_3' => '',
                'flag' => 'gb-sct.png',
                'country_code' => '',
                'slug' => 'scotland',
                'is_active' => false,
            ],
            [
                'name' => 'Senegal',
                'arabic_name' => '',
                'iso_code_2' => 'sn',
                'iso_code_3' => '',
                'flag' => 'sn.png',
                'country_code' => '',
                'slug' => 'senegal',
                'is_active' => false,
            ],
            [
                'name' => 'Serbia',
                'arabic_name' => '',
                'iso_code_2' => 'rs',
                'iso_code_3' => '',
                'flag' => 'rs.png',
                'country_code' => '',
                'slug' => 'serbia',
                'is_active' => false,
            ],
            [
                'name' => 'Seychelles',
                'arabic_name' => '',
                'iso_code_2' => 'sc',
                'iso_code_3' => '',
                'flag' => 'sc.png',
                'country_code' => '',
                'slug' => 'seychelles',
                'is_active' => false,
            ],
            [
                'name' => 'Sierra Leone',
                'arabic_name' => '',
                'iso_code_2' => 'sl',
                'iso_code_3' => '',
                'flag' => 'sl.png',
                'country_code' => '',
                'slug' => 'sierra-leone',
                'is_active' => false,
            ],
            [
                'name' => 'Singapore',
                'arabic_name' => '',
                'iso_code_2' => 'sg',
                'iso_code_3' => '',
                'flag' => 'sg.png',
                'country_code' => '',
                'slug' => 'singapore',
                'is_active' => false,
            ],
            [
                'name' => 'Sint Maarten',
                'arabic_name' => '',
                'iso_code_2' => 'sx',
                'iso_code_3' => '',
                'flag' => 'sx.png',
                'country_code' => '',
                'slug' => 'sint-maarten',
                'is_active' => false,
            ],
            [
                'name' => 'Slovakia',
                'arabic_name' => '',
                'iso_code_2' => 'sk',
                'iso_code_3' => '',
                'flag' => 'sk.png',
                'country_code' => '',
                'slug' => 'slovakia',
                'is_active' => false,
            ],
            [
                'name' => 'Slovenia',
                'arabic_name' => '',
                'iso_code_2' => 'si',
                'iso_code_3' => '',
                'flag' => 'si.png',
                'country_code' => '',
                'slug' => 'slovenia',
                'is_active' => false,
            ],
            [
                'name' => 'Solomon Islands',
                'arabic_name' => '',
                'iso_code_2' => 'sb',
                'iso_code_3' => '',
                'flag' => 'sb.png',
                'country_code' => '',
                'slug' => 'solomon-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Somalia',
                'arabic_name' => '',
                'iso_code_2' => 'so',
                'iso_code_3' => '',
                'flag' => 'so.png',
                'country_code' => '',
                'slug' => 'somalia',
                'is_active' => false,
            ],
            [
                'name' => 'South Africa',
                'arabic_name' => '',
                'iso_code_2' => 'za',
                'iso_code_3' => '',
                'flag' => 'za.png',
                'country_code' => '',
                'slug' => 'south-africa',
                'is_active' => false,
            ],
            [
                'name' => 'South Georgia',
                'arabic_name' => '',
                'iso_code_2' => 'gs',
                'iso_code_3' => '',
                'flag' => 'gs.png',
                'country_code' => '',
                'slug' => 'south-georgia',
                'is_active' => false,
            ],
            [
                'name' => 'South Korea',
                'arabic_name' => '',
                'iso_code_2' => 'kr',
                'iso_code_3' => '',
                'flag' => 'kr.png',
                'country_code' => '',
                'slug' => 'south-korea',
                'is_active' => false,
            ],
            [
                'name' => 'South Sudan',
                'arabic_name' => '',
                'iso_code_2' => 'ss',
                'iso_code_3' => '',
                'flag' => 'ss.png',
                'country_code' => '',
                'slug' => 'south-sudan',
                'is_active' => false,
            ],
            [
                'name' => 'Spain',
                'arabic_name' => '',
                'iso_code_2' => 'es',
                'iso_code_3' => '',
                'flag' => 'es.png',
                'country_code' => '',
                'slug' => 'spain',
                'is_active' => false,
            ],
            [
                'name' => 'Sri Lanka',
                'arabic_name' => '',
                'iso_code_2' => 'lk',
                'iso_code_3' => '',
                'flag' => 'lk.png',
                'country_code' => '',
                'slug' => 'sri-lanka',
                'is_active' => false,
            ],
            [
                'name' => 'Sudan',
                'arabic_name' => '',
                'iso_code_2' => 'sd',
                'iso_code_3' => '',
                'flag' => 'sd.png',
                'country_code' => '',
                'slug' => 'sudan',
                'is_active' => false,
            ],
            [
                'name' => 'Suriname',
                'arabic_name' => '',
                'iso_code_2' => 'sr',
                'iso_code_3' => '',
                'flag' => 'sr.png',
                'country_code' => '',
                'slug' => 'suriname',
                'is_active' => false,
            ],
            [
                'name' => 'Svalbard and Jan Mayen',
                'arabic_name' => '',
                'iso_code_2' => 'sj',
                'iso_code_3' => '',
                'flag' => 'sj.png',
                'country_code' => '',
                'slug' => 'svalbard-and-jan-mayen',
                'is_active' => false,
            ],
            [
                'name' => 'Sweden',
                'arabic_name' => '',
                'iso_code_2' => 'se',
                'iso_code_3' => '',
                'flag' => 'se.png',
                'country_code' => '',
                'slug' => 'sweden',
                'is_active' => false,
            ],
            [
                'name' => 'Switzerland',
                'arabic_name' => '',
                'iso_code_2' => 'ch',
                'iso_code_3' => '',
                'flag' => 'ch.png',
                'country_code' => '',
                'slug' => 'switzerland',
                'is_active' => false,
            ],
            [
                'name' => 'Syria',
                'arabic_name' => '',
                'iso_code_2' => 'sy',
                'iso_code_3' => '',
                'flag' => 'sy.png',
                'country_code' => '',
                'slug' => 'syria',
                'is_active' => false,
            ],
            [
                'name' => 'Taiwan',
                'arabic_name' => '',
                'iso_code_2' => 'tw',
                'iso_code_3' => '',
                'flag' => 'tw.png',
                'country_code' => '',
                'slug' => 'taiwan',
                'is_active' => false,
            ],
            [
                'name' => 'Tajikistan',
                'arabic_name' => '',
                'iso_code_2' => 'tj',
                'iso_code_3' => '',
                'flag' => 'tj.png',
                'country_code' => '',
                'slug' => 'tajikistan',
                'is_active' => false,
            ],
            [
                'name' => 'Tanzania',
                'arabic_name' => '',
                'iso_code_2' => 'tz',
                'iso_code_3' => '',
                'flag' => 'tz.png',
                'country_code' => '',
                'slug' => 'tanzania',
                'is_active' => false,
            ],
            [
                'name' => 'Thailand',
                'arabic_name' => '',
                'iso_code_2' => 'th',
                'iso_code_3' => '',
                'flag' => 'th.png',
                'country_code' => '',
                'slug' => 'thailand',
                'is_active' => false,
            ],
            [
                'name' => 'Timor-Leste',
                'arabic_name' => '',
                'iso_code_2' => 'tl',
                'iso_code_3' => '',
                'flag' => 'tl.png',
                'country_code' => '',
                'slug' => 'timor-leste',
                'is_active' => false,
            ],
            [
                'name' => 'Togo',
                'arabic_name' => '',
                'iso_code_2' => 'tg',
                'iso_code_3' => '',
                'flag' => 'tg.png',
                'country_code' => '',
                'slug' => 'togo',
                'is_active' => false,
            ],
            [
                'name' => 'Tokelau',
                'arabic_name' => '',
                'iso_code_2' => 'tk',
                'iso_code_3' => '',
                'flag' => 'tk.png',
                'country_code' => '',
                'slug' => 'tokelau',
                'is_active' => false,
            ],
            [
                'name' => 'Tonga',
                'arabic_name' => '',
                'iso_code_2' => 'to',
                'iso_code_3' => '',
                'flag' => 'to.png',
                'country_code' => '',
                'slug' => 'tonga',
                'is_active' => false,
            ],
            [
                'name' => 'Trinidad and Tobago',
                'arabic_name' => '',
                'iso_code_2' => 'tt',
                'iso_code_3' => '',
                'flag' => 'tt.png',
                'country_code' => '',
                'slug' => 'trinidad-and-tobago',
                'is_active' => false,
            ],
            [
                'name' => 'Tunisia',
                'arabic_name' => '',
                'iso_code_2' => 'tn',
                'iso_code_3' => '',
                'flag' => 'tn.png',
                'country_code' => '',
                'slug' => 'tunisia',
                'is_active' => false,
            ],
            [
                'name' => 'Turkey',
                'arabic_name' => '',
                'iso_code_2' => 'tr',
                'iso_code_3' => '',
                'flag' => 'tr.png',
                'country_code' => '',
                'slug' => 'turkey',
                'is_active' => false,
            ],
            [
                'name' => 'Turkmenistan',
                'arabic_name' => '',
                'iso_code_2' => 'tm',
                'iso_code_3' => '',
                'flag' => 'tm.png',
                'country_code' => '',
                'slug' => 'turkmenistan',
                'is_active' => false,
            ],
            [
                'name' => 'Turks and Caicos Islands',
                'arabic_name' => '',
                'iso_code_2' => 'tc',
                'iso_code_3' => '',
                'flag' => 'tc.png',
                'country_code' => '',
                'slug' => 'turks-and-caicos-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Tuvalu',
                'arabic_name' => '',
                'iso_code_2' => 'tv',
                'iso_code_3' => '',
                'flag' => 'tv.png',
                'country_code' => '',
                'slug' => 'tuvalu',
                'is_active' => false,
            ],
            [
                'name' => 'Uganda',
                'arabic_name' => '',
                'iso_code_2' => 'ug',
                'iso_code_3' => '',
                'flag' => 'ug.png',
                'country_code' => '',
                'slug' => 'uganda',
                'is_active' => false,
            ],
            [
                'name' => 'Ukraine',
                'arabic_name' => '',
                'iso_code_2' => 'ua',
                'iso_code_3' => '',
                'flag' => 'ua.png',
                'country_code' => '',
                'slug' => 'ukraine',
                'is_active' => false,
            ],
            [
                'name' => 'United Arab Emirates',
                'arabic_name' => '',
                'iso_code_2' => 'ae',
                'iso_code_3' => '',
                'flag' => 'ae.png',
                'country_code' => '',
                'slug' => 'united-arab-emirates',
                'is_active' => false,
            ],
            [
                'name' => 'United Kingdom',
                'arabic_name' => '',
                'iso_code_2' => 'gb',
                'iso_code_3' => '',
                'flag' => 'gb.png',
                'country_code' => '',
                'slug' => 'united-kingdom',
                'is_active' => false,
            ],
            [
                'name' => 'United States',
                'arabic_name' => 'الولايات المتحدة',
                'iso_code_2' => 'us',
                'iso_code_3' => 'usa',
                'flag' => 'us.png',
                'country_code' => '+10',
                'slug' => 'united-states',
                'is_active' => true,
            ],
            [
                'name' => 'United States Minor Outlying Islands',
                'arabic_name' => '',
                'iso_code_2' => 'um',
                'iso_code_3' => '',
                'flag' => 'um.png',
                'country_code' => '',
                'slug' => 'united-states-minor-outlying-islands',
                'is_active' => false,
            ],
            [
                'name' => 'United States Virgin Islands',
                'arabic_name' => '',
                'iso_code_2' => 'vi',
                'iso_code_3' => '',
                'flag' => 'vi.png',
                'country_code' => '',
                'slug' => 'united-states-virgin-islands',
                'is_active' => false,
            ],
            [
                'name' => 'Uruguay',
                'arabic_name' => '',
                'iso_code_2' => 'uy',
                'iso_code_3' => '',
                'flag' => 'uy.png',
                'country_code' => '',
                'slug' => 'uruguay',
                'is_active' => false,
            ],
            [
                'name' => 'Uzbekistan',
                'arabic_name' => '',
                'iso_code_2' => 'uz',
                'iso_code_3' => '',
                'flag' => 'uz.png',
                'country_code' => '',
                'slug' => 'uzbekistan',
                'is_active' => false,
            ],
            [
                'name' => 'Vanuatu',
                'arabic_name' => '',
                'iso_code_2' => 'vu',
                'iso_code_3' => '',
                'flag' => 'vu.png',
                'country_code' => '',
                'slug' => 'vanuatu',
                'is_active' => false,
            ],
            [
                'name' => 'Vatican City',
                'arabic_name' => '',
                'iso_code_2' => 'va',
                'iso_code_3' => '',
                'flag' => 'va.png',
                'country_code' => '',
                'slug' => 'vatican-city',
                'is_active' => false,
            ],
            [
                'name' => 'Venezuela',
                'arabic_name' => '',
                'iso_code_2' => 've',
                'iso_code_3' => '',
                'flag' => 've.png',
                'country_code' => '',
                'slug' => 'venezuela',
                'is_active' => false,
            ],
            [
                'name' => 'Vietnam',
                'arabic_name' => '',
                'iso_code_2' => 'vn',
                'iso_code_3' => '',
                'flag' => 'vn.png',
                'country_code' => '',
                'slug' => 'vietnam',
                'is_active' => false,
            ],
            [
                'name' => 'Wales',
                'arabic_name' => '',
                'iso_code_2' => 'gb-wls',
                'iso_code_3' => '',
                'flag' => 'gb-wls.png',
                'country_code' => '',
                'slug' => 'wales',
                'is_active' => false,
            ],
            [
                'name' => 'Wallis and Futuna',
                'arabic_name' => '',
                'iso_code_2' => 'wf',
                'iso_code_3' => '',
                'flag' => 'wf.png',
                'country_code' => '',
                'slug' => 'wallis-and-futuna',
                'is_active' => false,
            ],
            [
                'name' => 'Western Sahara',
                'arabic_name' => '',
                'iso_code_2' => 'eh',
                'iso_code_3' => '',
                'flag' => 'eh.png',
                'country_code' => '',
                'slug' => 'western-sahara',
                'is_active' => false,
            ],
            [
                'name' => 'Yemen',
                'arabic_name' => '',
                'iso_code_2' => 'ye',
                'iso_code_3' => '',
                'flag' => 'ye.png',
                'country_code' => '',
                'slug' => 'yemen',
                'is_active' => false,
            ],
            [
                'name' => 'Zambia',
                'arabic_name' => '',
                'iso_code_2' => 'zm',
                'iso_code_3' => '',
                'flag' => 'zm.png',
                'country_code' => '',
                'slug' => 'zambia',
                'is_active' => false,
            ],
            [
                'name' => 'Zimbabwe',
                'arabic_name' => '',
                'iso_code_2' => 'zw',
                'iso_code_3' => '',
                'flag' => 'zw.png',
                'country_code' => '',
                'slug' => 'zimbabwe',
                'is_active' => false,
            ]
        ];

        Country::insert($countries);
    }
}
